name: helm-upgrade
run-name: ${{ github.actor}} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './todoapp/values.yaml'
      DockerImageName:
        type: string
        required: true
      helm-release-name:
        type: string
        default: todoapp

jobs:
  deploy-helm:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download Helm Package
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Download Helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Download Cluster Artifact
        uses: actions/download-artifact@v4
        with:
          name: cluster-artifact
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: tdacluster
          config: ./cluster.yml

      - name: Preview Helm Install
        run: helm install --dry-run

      - name: Deploy helm to Development
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY}}" \
          --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME}}" \
          --set todoapp.secrets.DB_USER="${{ secrets.DB_USER}}" \
          --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD}}" \
          --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST}}" \
          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD}}" \
          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER}}" \
          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD}}" \
          --set todoapp.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.DockerImageName }} \
          --set todoapp.image.tag=${{ github.sha }}
