name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name}} -${{ github.sha }}

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]

env:
  PythonVersion: 3.8
  DockerImageName: todoapp

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PythonVersion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PythonVersion }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Generate Report
        run: |
          coverage run --source='.' manage.py test
          coverage report

      - name: Linting
        run: |
          flake8 . --show-source --statistics --exit-zero

      - name: Check Complexity
        run: |
          flake8 . --exit-zero --max-complexity=6

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: .

      - name: Upload helm artifacts
        if: github.ref_name == 'develop'
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: ${{ github.workspace }}/helm-charts

      - name: Upload cluster artifact
        if: github.ref_name == 'develop'
        uses: actions/upload-artifact@v4
        with:
          name: cluster-artifact
          path: ${{ github.workspace }}/cluster.yml

  docker-ci:
    name: Build and Push Image
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'develop' }}
    needs: python-ci
    steps:

    - uses: actions/download-artifact@v4
      name: Download python artifacts
      with:
        name: python-artifacts
        path: .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./src
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }}:${{ github.sha }}

  helm-ci:
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.ref_name == 'develop'
    name: Helm CI
    steps:

    - uses: actions/download-artifact@v4
      with:
        name: helm-artifacts
        path: .

    - name: Set Up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Lint helm
      run: helm lint ./todoapp/

    - name: Template Helm
      run: helm template todoapp ./todoapp/ -f ./todoapp/values.yaml

    - name: Package Helm
      run: helm package ./todoapp

    - name: Upload Helm Artifact
      uses: actions/upload-artifact@v4
      with:
        name: helm-package
        path: ./*.tgz

  deploy-helm:
    name: Deploy helm
    needs: [docker-ci, helm-ci]
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Download Helm Package
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Download Helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Download Cluster Artifact
        uses: actions/download-artifact@v4
        with:
          name: cluster-artifact
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          config: ./cluster.yml

      - name: Deploy helm to Development
        run: |
          helm-upgrade --install --dry-run --atomic --wait --timeout 3600s --debug todoapp ./todoapp.tgz \
          -f ./todoapp/values.yaml \
          --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY}}" \
          --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME}}" \
          --set todoapp.secrets.DB_USER="${{ secrets.DB_USER}}" \
          --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD}}" \
          --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST}}" \
          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD}}" \
          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER}}" \
          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD}}" \
          --set todoapp.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
          --set todoapp.image.tag=${{ github.sha }}
